/* SGS RSL Failure Center V3.2G
   Verified SGS Korea PFAS parser + supplier notification workflow.
*/
(() => {
'use strict';
const $=id=>document.getElementById(id);let failedItems=[];
const clean=v=>String(v||'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pageText=c=>clean((c.items||[]).map(x=>String(x.str||'').trim()).filter(Boolean).join(' '));
function reportNo(t){for(const p of [/Test\s+Report\s+No\.?\s*[:#]?\s*([A-Z0-9][A-Z0-9/_\-\s]{5,80}?)(?=\s+(?:Issued\s+Date|Date|Page|This\s+document))/i,/Report\s+No\.?\s*[:#]?\s*([A-Z0-9][A-Z0-9/_\-\s]{5,80}?)(?=\s+(?:Issued\s+Date|Date|Page|Applicant))/i]){const m=clean(t).match(p);if(m)return m[1].trim().replace(/[／⁄∕]/g,'/').replace(/[–—−]/g,'-').replace(/\s*\/\s*/g,'/').replace(/\s*-\s*/g,'-').replace(/\s+/g,'').replace(/[^A-Z0-9/_-]/gi,'')}return''}
function issuedDate(t){const m=clean(t).match(/Issued\s+Date\s*[:#]?\s*(\d{4})[.\/-](\d{1,2})[.\/-](\d{1,2})/i);return m?`${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`:''}
function requirement(t,label){const s=clean(t),e=label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),ps=[new RegExp(`(?:^|\\s)${e}\\s+\\d+(?:\\.\\d+)?\\s*ppb\\s*\\((\\d+(?:\\.\\d+)?)\\s*mg\\/kg\\)`,'gi'),new RegExp(`(?:^|\\s)${e}\\s+(\\d+(?:\\.\\d+)?)\\s*mg\\/kg`,'gi')],a=[];for(const p of ps){let m;while((m=p.exec(s))){a.push({i:m.index,v:+m[1]});if(p.lastIndex===m.index)p.lastIndex++}}return a.length?a.sort((x,y)=>x.i-y.i).at(-1).v:null}
function casResult(t,cas){const e=cas.replace(/-/g,'\\-'),m=clean(t).match(new RegExp(`${e}\\s+(\\d+(?:\\.\\d+)?)\\s+(n\\.?d\\.?|not detected|\\d+(?:\\.\\d+)?)`,'i'));return !m||/n\.?d\.?|not detected/i.test(m[2])?null:+m[2]}
function totalResult(t,label){const e=label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),m=clean(t).match(new RegExp(`${e}\\s+--\\s+--\\s+(n\\.?d\\.?|not detected|\\d+(?:\\.\\d+)?)`,'i'));return !m||/n\.?d\.?|not detected/i.test(m[1])?null:+m[1]}
const item=(n,r,l)=>({substance:n,result:`${r} mg/kg`,limit:`${l} mg/kg`});
function parsePFAS(t){const s=clean(t);if(!/Per-\s*&?\s*Polyfluoroalkyl\s+Substances\s*\(PFAS\)|PFAS\s*-\s*Target\s+Analysis/i.test(s)||!/Conclusion\s*(?:--\s*){0,2}FAIL\s*\*/i.test(s))return[];const out=[],defs=[['6:2 FTOH','647-42-7','PFHxA-related Substances'],['8:2 FTOH','678-39-7','PFOA-related Substances'],['10:2 FTOH','865-86-1','C9-C14 PFCA-related Substances'],['12:2 FTOH','39239-77-5','C9-C14 PFCA-related Substances']];for(const[n,c,g]of defs){const r=casResult(s,c),l=requirement(s,g);if(r!==null&&l!==null&&r>l)out.push(item(n,r,l))}const tots=[['Total PFHxA-related Substances','Total PFHxA-related Substances','PFHxA-related Substances'],['Total PFOA-related Substances','Total of PFOA-related Substances','PFOA-related Substances'],['Total C9-C14 PFCA-related Substances','Total of C9-C14 PFCA-related Substances','C9-C14 PFCA-related Substances']];for(const[n,x,g]of tots){const r=totalResult(s,x),l=requirement(s,g);if(r!==null&&l!==null&&r>l)out.push(item(n,r,l))}return out}
function parseBisphenols(t){const s=clean(t),sec=s.match(/Bisphenols[\s\S]{0,1800}?(?=Chlorobenzenes|Forbidden|Formaldehyde|$)/i)?.[0]||'';if(!sec||!/Conclusion\s*(?:--\s*)?FAIL\s*\*/i.test(sec))return[];const bpa=requirement(sec,'BPA'),m=sec.match(/BPS\s*,?\s*BPB\s*,?\s*BPF\s+(\d+(?:\.\d+)?)\s*mg\/kg/i),other=m?+m[1]:null,defs=[['BPA','80-05-7',bpa],['BPS','80-09-1',other],['BPB','77-40-7',other],['BPF','620-92-8',other]];return defs.flatMap(([n,c,l])=>{const r=casResult(sec,c);return r!==null&&l!==null&&r>l?[item(n,r,l)]:[]})}
function dedupe(a){const m=new Map();a.forEach(x=>m.set(`${x.substance}|${x.result}|${x.limit}`.toUpperCase(),x));return[...m.values()]}
function installUI(){if($('failedItemsV32'))return;const s=$('substance');if(!s)return;const fs=[s.closest('.field'),$('result').closest('.field'),$('limit').closest('.field')];fs.forEach(x=>x.style.display='none');const w=document.createElement('div');w.id='failedItemsV32';w.className='field full';w.innerHTML='<label>Failed Items *</label><div id="failedItemsRows"></div><button type="button" class="btn" id="addFailedItemV32">+ Add Failed Item</button>';fs[0].parentElement.insertBefore(w,fs[0]);$('addFailedItemV32').onclick=()=>{failedItems.push({substance:'',result:'',limit:''});render()};render()}
function render(){const h=$('failedItemsRows');if(!h)return;h.innerHTML=failedItems.map((x,i)=>`<div style="display:grid;grid-template-columns:1.5fr 1fr 1fr auto;gap:8px;margin:8px 0"><input data-k="substance" data-i="${i}" value="${esc(x.substance)}" placeholder="Substance / Test Item"><input data-k="result" data-i="${i}" value="${esc(x.result)}" placeholder="Measured Result"><input data-k="limit" data-i="${i}" value="${esc(x.limit)}" placeholder="Limit"><button type="button" class="btn danger" data-r="${i}">Remove</button></div>`).join('');h.querySelectorAll('[data-k]').forEach(n=>n.oninput=()=>{failedItems[+n.dataset.i][n.dataset.k]=n.value;sync()});h.querySelectorAll('[data-r]').forEach(n=>n.onclick=()=>{failedItems.splice(+n.dataset.r,1);render()});sync()}
function sync(){const x=failedItems[0]||{};$('substance').value=x.substance||'';$('result').value=x.result||'';$('limit').value=x.limit||''}
function email(c){const a=c.failedItems?.length?c.failedItems:failedItems,p=$('emailPreview');if(!p)return;const list=a.map((x,i)=>`${i+1}. ${x.substance}\n   Test result: ${x.result}\n   Requirement / limit: ${x.limit}`).join('\n\n');p.textContent=`Subject: SGS RSL Failure Case Established | ${c.article} | Report ${c.report}\n\nDear ${c.supplier} Team,\n\nA Failure Case has been established based on SGS RSL Report ${c.report} for Fabric Article ${c.article}${c.po?`, PO(s) ${c.po}`:''}${c.lot?`, Lot(s) ${c.lot}`:''}.\n\nFailed Items\n\n${list}\n\nImmediate action is required. Please immediately quarantine all affected material and stop shipment, cutting, production use, transfer, or release until Vuori provides the next written instruction.\n\nPlease provide the following information so that Vuori can assess the impact and determine the next action.\n\nImmediate Containment\n1. Possible Root Cause Analysis\n2. Affected quantity\n3. Affected PO(s)\n4. Affected lot(s)\n5. Current inventory status\n6. Quarantine / Hold status\n7. Material disposition plan\n\nRetest Plan\n1. Full PFAS package retest plan\n   Retesting must cover the complete PFAS package, not only the failed analyte.\n2. Sample submission date\n3. Expected report completion date\n4. SGS TRF # once available\n\nPlease provide the above information at your earliest convenience so that Vuori can evaluate the next steps and determine the appropriate disposition.\n\nThank you for your immediate attention and cooperation.\n\nBest regards,\nVuori Product Integrity & Compliance`;$('emailCard')?.classList.remove('hidden')}
function install(){installUI();const a=$('analyzePdf'),base=a?.onclick;if(a)a.onclick=async function(e){await base?.call(this,e);const f=$('pdfFile')?.files?.[0];if(!f)return;try{const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise,p=[];for(let i=1;i<=pdf.numPages;i++)p.push(pageText(await(await pdf.getPage(i)).getTextContent()));const head=p.slice(0,3).join(' '),rn=reportNo(head),dt=issuedDate(head);if(rn)$('report').value=rn;if(dt)$('reportDate').value=dt;let all=[];for(let i=0;i<p.length;i++){const sec=[p[i],p[i+1]||'',p[i+2]||''].join(' ');all=all.concat(parsePFAS(sec),parseBisphenols(sec))}failedItems=dedupe(all);render();const x=$('parseAlert');if(x){x.textContent=failedItems.length?`Automated extraction completed. ${failedItems.length} failed item(s) listed.${rn?` Official Report #: ${rn}.`:''} Verify each item against the original PDF.`:`No supported failed section was confirmed.${rn?` Official Report #: ${rn}.`:''} Add failed items manually.`;x.classList.remove('hidden')}}catch(err){console.error('SGS RSL V3.2G',err)}};const b=$('createCase'),bc=b?.onclick;if(b)b.onclick=function(e){sync();if(!failedItems.length||failedItems.some(x=>!x.substance||!x.result||!x.limit)){alert('Complete each Failed Item before creating the case.');return}const n=cases.length;bc?.call(this,e);if(cases.length>n){cases[0].failedItems=JSON.parse(JSON.stringify(failedItems));localStorage.setItem(CASE_KEY,JSON.stringify(cases));renderCases?.();email(cases[0])}};window.generateEmail=email;document.addEventListener('click',e=>{const b=e.target.closest('[data-email]');if(!b)return;const c=cases.find(x=>x.id===b.dataset.email);if(c)setTimeout(()=>email(c),0)},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
