/* SGS RSL Smart Parser V26
   Supports SGS Korea, Hong Kong, Taiwan and Vietnam text-based reports.
   Categories: PFAS, Bisphenols, TOF, pH, AP/APEO, Total/Extractable Heavy Metals, Phthalates/DEHP.
*/
(() => {
'use strict';
const $=id=>document.getElementById(id);
const clean=v=>String(v||'').replace(/\u00a0/g,' ').replace(/[‐‑‒–—−]/g,'-').replace(/\s+/g,' ').trim();
const compact=v=>clean(v).toLowerCase().replace(/\s+/g,'');
const numeric=v=>{const m=String(v||'').replace(/,/g,'').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):null};
const unique=a=>[...new Map(a.map(x=>[`${x.substance}|${x.result}|${x.limit}|${x.component}`.toLowerCase(),x])).values()];
const item=(substance,result,limit,component='',conclusion='FAIL',remarks='')=>({substance:clean([substance,component&&`Component ${component}`].filter(Boolean).join(' | ')),result:clean(result),limit:clean(limit),component:clean(component),conclusion:clean(conclusion),remarks:clean(remarks)});
let v26Items=[];
function first(t,patterns){for(const p of patterns){const m=t.match(p);if(m)return clean(m[1])}return''}
function valid(v){return v&&!/^(?:n\/?a|\/|-|not applicable)$/i.test(clean(v))}
function reportNo(t){let v=first(t,[
 /Textile\s+Laboratory\s+Test\s+Report\s+No\s*:\s*([A-Z0-9]+\s*\/\s*\d{4}\s*\/\s*[A-Z0-9-]+)/i,
 /Test\s+Report\s+No\.?\s*[:.]?\s*([A-Z0-9][A-Z0-9\/_\-\s]{5,80}?)(?=\s+(?:Issued\s+Date|Date|Page|This\s+document))/i,
 /Test\s+Report\s+No\s*\.\s*:\s*([A-Z0-9][A-Z0-9\/_\-\s]{5,80}?)(?=\s+Date)/i,
 /Test\s+Report\s+([A-Z]{2,5}\d{7,}(?:-\d+)?)(?=\s+Date)/i,
 /\bNo\.?\s*:\s*([A-Z]{2,5}\d{7,}(?:-\d+)?)(?=\s+Date)/i
 ]);return clean(v).replace(/\s*\/\s*/g,'/').replace(/\s*-\s*/g,'-').replace(/\s+/g,'')}
function dateIso(t){const s=first(t,[/Issued\s+Date\s*:\s*([A-Za-z]{3,9}\.?\s+\d{1,2},?\s+\d{4}|\d{4}\s*[.\/-]\s*\d{1,2}\s*[.\/-]\s*\d{1,2})/i,/\bDate\s*:\s*([A-Za-z]{3,9}\.?\s+\d{1,2},?\s+\d{4}|\d{4}\s*[.\/-]\s*\d{1,2}\s*[.\/-]\s*\d{1,2})/i]);if(!s)return'';const m=s.match(/(\d{4})\s*[.\/-]\s*(\d{1,2})\s*[.\/-]\s*(\d{1,2})/);if(m)return`${m[1]}-${m[2].padStart(2,'0')}-${m[3].padStart(2,'0')}`;const d=new Date(s.replace(/\./g,' '));return isNaN(d)?'':d.toISOString().slice(0,10)}
function field(t,label,next){const p=new RegExp(`${label}\\s*:?\\s*(.{1,180}?)(?=\\s+(?:${next}))`,'i'),m=t.match(p);return m?clean(m[1]).replace(/^\*+|\*+$/g,'').trim():''}
function header(t){
 const supplier=first(t,[/Supplier\s+Company\s+Name\s*:\s*([^*]{2,100}?)(?=\s+(?:Sample\s+Type|Division|Department))/i,/APPLICANT\s*:\s*([^*]{2,100}?)(?=\s+(?:OVERALL|APPLICANT\s+ADDRESS))/i,/Applicant\s*:\s*([^*]{2,100}?)(?=\s+OVERALL)/i]);
 return{report:reportNo(t),reportDate:dateIso(t),supplier:clean(supplier),article:field(t,'Article\\s+Number','Agent\\s+Name|Manufacturer|Construction'),po:field(t,'PO#\\s*\\/\\s*Ref#','Bulk\\s+Lot#|Style'),lot:field(t,'Bulk\\s+Lot#','Style\\s*#|Style\\s+Name'),color:field(t,'Color','Article\\s+Number|Agent\\s+Name')};
}
function components(t){const out={};let m;const p=/(?:Test\s+Component\s+ID\s+for\s+Report\s*:\s*)?(\d+|[A-Z]\d*)\.?32?\s+(.{3,120}?)(?=\s+(?:\d+|[A-Z]\d*)\.?\s+|\s+Test\s+Result|$)/gi;while((m=p.exec(t)))out[m[1]]=clean(m[2]);return out}
function parsePH(t){const out=[];const re=/p\s*H\s*Value[\s\S]{0,500}?Result\s+CAS-?No\.?\s+([A-Z]?\d*)[\s\S]{0,160}?p\s*H\s*Value\s+--\s*(\d+(?:\.\d+)?)[\s\S]{0,120}?Conclusion\s+--\s*(FAIL\*?|PASS)[\s\S]{0,260}?Requirement\s*:\s*(\d+(?:\.\d+)?\s*-\s*\d+(?:\.\d+)?)/i;const m=t.match(re);if(m&&/FAIL/i.test(m[3]))out.push(item('pH Value',m[2],m[4],m[1],m[3]));return out}
function parseBisphenols(t){const out=[];const sections=t.match(/Bisphenols(?:\s+Content)?[\s\S]{0,1800}?(?=(?:Test\s+Result\s*:|Forbidden|Chlorobenzenes|Formaldehyde|$))/gi)||[];const defs=[['Bisphenol A (BPA)','80-05-7','BPA'],['Bisphenol S (BPS)','80-09-1','BPS'],['Bisphenol B (BPB)','77-40-7','BPB'],['Bisphenol F (BPF)','620-92-8','BPF'],['Bisphenol AF (BPAF)','1478-61-1','BPAF']];for(const s of sections){if(!/Conclusion\s*--?\s*FAIL/i.test(s))continue;for(const[name,cas,abbr]of defs){const r=s.match(new RegExp(`${abbr.replace(/[()]/g,'\\$&')}\\)?\\s+${cas.replace(/-/g,'\\-')}\\s+(?:ppm\\s+0\\.10\\s+)?(ND|n\\.d\\.|\\d+(?:\\.\\d+)?)`,'i'));if(!r||/ND|n\.d/i.test(r[1]))continue;let lim=null;const direct=s.match(new RegExp(`(?:Req\\.?|Requirement|Client.?s Limit)[\\s\\S]{0,350}?${abbr}[^\\d]{0,30}(\\d+(?:\\.\\d+)?)\\s*(?:ppm|mg\\/kg)`,'i'));if(direct)lim=direct[1];if(lim===null){if(abbr==='BPS')lim='100';else lim='1'}if(numeric(r[1])>numeric(lim))out.push(item(`${name}, CAS ${cas}`,`${r[1]} mg/kg`,`${lim} mg/kg`,'', 'FAIL'));}}
 const summary=t.match(/Bisphenol\s+S\s*\(BPS\)\s*:\s*(\d+(?:\.\d+)?)\s*ppm[\s\S]{0,60}?(?:Req.?t|Requirement)\s*:\s*(\d+(?:\.\d+)?)\s*ppm/i);if(summary&&numeric(summary[1])>numeric(summary[2]))out.push(item('Bisphenol S (BPS), CAS 80-09-1',`${summary[1]} ppm`,`${summary[2]} ppm`));return unique(out)}
function parseTOF(t){const out=[];let m;const re=/(?:Total\s+Organic\s+Fluorine(?:\s+Content|\s+Screening)?|Fluorine\s+Content)[\s\S]{0,700}?Test\s+Item\(s\)\s*(?:Unit\(s\)\s+RL_?)?\s*([123ABC]?)[\s\S]{0,180}?(?:Total\s+Organic\s+Fluorine|Fluorine\s+Content)\s*(?:mg\/kg)?\s*(?:\d+(?:\.\d+)?\s+)?(ND|\d+(?:\.\d+)?)\s*(?:mg\/kg)?\s*#?[\s\S]{0,100}?Conclusion\s*(?:--)?\s*(FAIL#?|PASS)/gi;while((m=re.exec(t))){if(/FAIL/i.test(m[3])){const req=first(m[0],[/Req\.?\s*(\d+(?:\.\d+)?)/i,/Requirement\s*:?[\s\S]{0,30}?(\d+(?:\.\d+)?\s*mg\/kg|Not\s+Detected)/i])||first(t,[/Total\s+Organic\s+Fluorine[\s\S]{0,900}?Requirement\s*:?[\s\S]{0,30}?(\d+(?:\.\d+)?\s*mg\/kg|Not\s+Detected)/i]);out.push(item('Total Organic Fluorine (TOF)',`${m[2]} mg/kg`,req||'See report',m[1],m[3]))}}
 return unique(out)}
function parseAPEO(t){const sec=(t.match(/Alkylphenols\s*\(AP\)[\s\S]{0,1500}?Conclusion\s*--\s*FAIL\*?[\s\S]{0,400}?Requirement[\s\S]{0,150}/i)||[])[0];if(!sec)return[];const r=first(sec,[/Total\s*AP\s*\+\s*APEO\s+(?:various\s+)?(\d+(?:\.\d+)?)/i,/T\s*otal\s*AP\s*\+\s*APEO\s+(?:v\s*arious\s+)?(\d+(?:\.\d+)?)/i]);const l=first(sec,[/Total\s*AP\s*\+\s*APEO\s+(\d+(?:\.\d+)?)\s*mg\/kg/i])||'100';if(!r)return[];return[item('Total AP + APEO',`${r} mg/kg`,`${l} mg/kg`,'','FAIL',`Total APEO: ${r} mg/kg`)]}
function parseHeavyMetals(t){const out=[];const sections=t.match(/(?:Total|Extractable)\s+Heavy\s+Metal[\s\S]{0,1800}?(?=(?:Chromium\s+VI|Total\s+Lead|Phthalates|Organotin|Extractable\s+Heavy|$))/gi)||[];for(const s of sections){if(!/Conclusion\s*--[\s\S]{0,40}(?:FAIL|INTERIM-FAIL)/i.test(s))continue;const isExtract=/Extractable/i.test(s);const head=s.match(/Result\s*\(mg\/kg\)\s+CAS-?No\.?\s+([^\n]{1,30})/i)?.[1]||'';for(const[name,sym,cas]of[['Arsenic','As','7440-38-2'],['Cadmium','Cd','7440-43-9'],['Mercury','Hg','7439-97-6']]){const row=s.match(new RegExp(`${name}\\s*\\(${sym}\\)\\s+${cas.replace(/-/g,'\\-')}\\s+(ND|\\d+(?:\\.\\d+)?)\\s*(ND|\\d+(?:\\.\\d+)?)?`,'i'));if(!row)continue;const vals=[row[1],row[2]].filter(Boolean);vals.forEach((v,i)=>{if(/ND/i.test(v))return;let lim=sym==='As'?100:sym==='Cd'?40:0.5;if(isExtract)lim=sym==='As'?0.2:sym==='Cd'?0.1:0.02;const conclusion=/INTERIM-FAIL/i.test(s)&&i===0?'INTERIM-FAIL':'FAIL';if(numeric(v)>lim||/INTERIM-FAIL/i.test(conclusion))out.push(item(`${isExtract?'Extractable ':''}${name} (${sym}), CAS ${cas}`,`${v} mg/kg`,`${lim} mg/kg`,head.split(/\s+/)[i]||'',conclusion));});}}return unique(out)}
function parsePhthalates(t){const out=[];const sections=t.match(/Phthalates[\s\S]{0,2500}?Conclusion\s*--\s*FAIL\*?[\s\S]{0,500}?Requirement[\s\S]{0,150}/gi)||[];for(const s of sections){const r=s.match(/(?:Di\(2-ethylhexyl\)-phthalate|Bis-?\(2-ethylhexyl\)\s+Phthalate)\s*\(DEHP\)?\s+117-81-7\s+(\d+(?:\.\d+)?)/i);if(r){const lim=first(s,[/Requirement\s*:[\s\S]{0,80}?Each[^\d]*(\d+(?:\.\d+)?)\s*mg\/kg/i])||'500';out.push(item('Di(2-ethylhexyl) phthalate (DEHP), CAS 117-81-7',`${r[1]} mg/kg`,`${lim} mg/kg`,'3','FAIL'));}}return unique(out)}
function parseAll(t){return unique([...parsePH(t),...parseBisphenols(t),...parseTOF(t),...parseAPEO(t),...parseHeavyMetals(t),...parsePhthalates(t)])}
function ensureUI(){if($('failedItemsV26'))return;const s=$('substance');if(!s)return;[s,$('result'),$('limit')].forEach(x=>x.closest('.field').style.display='none');const w=document.createElement('div');w.id='failedItemsV26';w.className='field full';w.innerHTML='<label>Failed Items *</label><div id="failedItemsRowsV26"></div><button type="button" class="btn" id="addFailedItemV26">+ Add Failed Item</button>';s.closest('.field').parentElement.insertBefore(w,s.closest('.field'));$('addFailedItemV26').onclick=()=>{v26Items.push(item('','',''));renderItems()}}
function renderItems(){const h=$('failedItemsRowsV26');if(!h)return;h.innerHTML=v26Items.map((x,i)=>`<div style="display:grid;grid-template-columns:1.6fr 1fr 1fr auto;gap:8px;margin:8px 0"><input data-v26="substance" data-i="${i}" value="${x.substance.replace(/"/g,'&quot;')}" placeholder="Substance / Component"><input data-v26="result" data-i="${i}" value="${x.result.replace(/"/g,'&quot;')}" placeholder="Measured Result"><input data-v26="limit" data-i="${i}" value="${x.limit.replace(/"/g,'&quot;')}" placeholder="Limit"><button type="button" class="btn danger" data-rm-v26="${i}">Remove</button></div>`).join('');h.querySelectorAll('[data-v26]').forEach(n=>n.oninput=()=>{v26Items[+n.dataset.i][n.dataset.v26]=n.value;sync()});h.querySelectorAll('[data-rm-v26]').forEach(n=>n.onclick=()=>{v26Items.splice(+n.dataset.rmV26,1);renderItems()});sync()}
function sync(){const x=v26Items[0]||{};$('substance').value=x.substance||'';$('result').value=x.result||'';$('limit').value=x.limit||'';window.v26FailedItems=v26Items}
async function analyze(){const f=$('pdfFile')?.files?.[0];if(!f)return;const alert=$('parseAlert'),bar=$('parseBar');alert?.classList.add('hidden');if(bar)bar.style.width='8%';try{const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise,p=[];for(let i=1;i<=pdf.numPages;i++){const c=await(await pdf.getPage(i)).getTextContent();p.push(clean(c.items.map(x=>x.str).join(' ')));if(bar)bar.style.width=`${8+87*i/pdf.numPages}%`}const text=p.join('\n'),h=header(text);for(const[k,v]of Object.entries(h)){if($(k)&&valid(v))$(k).value=v}v26Items=parseAll(text);renderItems();$('workflow').value='Containment Required';if(!$('dueDate').value){const d=new Date();d.setDate(d.getDate()+14);$('dueDate').value=d.toISOString().slice(0,10)}$('immediate').value='Immediately quarantine all affected material. Stop shipment, cutting, production use, transfer and release pending written disposition.';if(bar)bar.style.width='100%';if(alert){alert.textContent=v26Items.length?`V26 extraction completed. ${v26Items.length} failed item(s) found. Verify all auto-filled values against the PDF.`:'No supported failed section was confirmed. Review the PDF and add failed items manually.';alert.classList.remove('hidden')}}catch(err){console.error('SGS Parser V26',err);if(alert){alert.textContent='The PDF text could not be parsed. Enter the fields manually.';alert.classList.remove('hidden')}if(bar)bar.style.width='0%'}}
function install(){ensureUI();const btn=$('analyzePdf');if(btn)btn.onclick=analyze;const create=$('createCase'),base=create?.onclick;if(create)create.onclick=function(e){sync();if(!v26Items.length||v26Items.some(x=>!x.substance||!x.result||!x.limit)){alert('Complete each Failed Item before creating the case.');return}const before=window.currentCase;base?.call(this,e);setTimeout(()=>{if(window.currentCase&&window.currentCase!==before){window.currentCase.failedItems=JSON.parse(JSON.stringify(v26Items));if(window.generateEmail)window.generateEmail(window.currentCase)}},0)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
