/* SGS RSL Failure Center V3.2B - strict parser */
(() => {
'use strict';
const $=id=>document.getElementById(id);
let items=[];
const analytes=[
 ['6:2 FTOH',/\b6\s*:\s*2\s*FTOH\b/i],['8:2 FTOH',/\b8\s*:\s*2\s*FTOH\b/i],
 ['PFOA',/\bPFOA\b|perfluorooctanoic acid/i],['PFOS',/\bPFOS\b|perfluorooctane sulfon/i],
 ['PFHxA',/\bPFHxA\b|perfluorohexanoic acid/i],['PFNA',/\bPFNA\b|perfluorononanoic acid/i],
 ['Total PFAS',/\btotal\s+PFAS\b/i],['TOF',/\bTOF\b|total organic fluorine/i],
 ['BPA',/\bBPA\b|bisphenol\s*A\b/i],['BPF',/\bBPF\b|bisphenol\s*F\b/i],
 ['BPS',/\bBPS\b|bisphenol\s*S\b/i],['BPB',/\bBPB\b|bisphenol\s*B\b/i],
 ['Total Bisphenols',/\btotal\s+bisphenols?\b/i],
 ['NPEO',/\bNPEO\b|nonylphenol ethoxylates?/i],['OPEO',/\bOPEO\b|octylphenol ethoxylates?/i],
 ['1,4-Dichlorobenzene',/1\s*,\s*4\s*-?\s*dichlorobenzene/i],
 ['Lead',/\blead\b/i],['Cadmium',/\bcadmium\b/i],['Mercury',/\bmercury\b/i],
 ['Chromium VI',/chromium\s*(?:VI|6)/i],['Arsenic',/\barsenic\b/i],['Nickel',/\bnickel\b/i]
];
const esc=v=>String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function rows(content){const m=new Map();for(const it of content.items||[]){const t=String(it.str||'').trim();if(!t)continue;const x=+it.transform[4],y=Math.round(+it.transform[5]/2)*2;if(!m.has(y))m.set(y,[]);m.get(y).push({x,t})}return[...m].sort((a,b)=>b[0]-a[0]).map(([y,a])=>a.sort((a,b)=>a.x-b.x).map(x=>x.t).join(' ').replace(/\s+/g,' '))}
function vals(t){const a=[],r=/([<>≤≥]?\s*(?:ND|N\.D\.|not detected|\d+(?:\.\d+)?)(?:\s*\*)?)\s*(mg\/kg|ppm|µg\/g|ug\/g|ng\/g|µg\/kg|ug\/kg|ppb|pH)/gi;let m;while((m=r.exec(t))){a.push({raw:(m[1]+' '+m[2]).replace(/\s+/g,' ').trim(),unit:m[2].toLowerCase(),star:/\*/.test(m[1]),index:m.index})}return a}
function requirement(all,i,unit){for(let d=0;d<=3;d++)for(const j of d?[i-d,i+d]:[i]){if(j<0||j>=all.length)continue;if(!/(?:requirement|limit|specification)/i.test(all[j]))continue;const v=vals(all[j]).filter(x=>x.unit===unit);if(v.length)return v[v.length-1]}return null}
function parse(all){const out=[];all.forEach((line,i)=>{if(/CAS[- ]?No|test method|reporting limit|fiber|fibre|composition|content|page\s+\d+\s+of|80% of/i.test(line))return;for(const [name,re] of analytes){if(!re.test(line)||/BPAF|bisphenol\s*AF/i.test(line))continue;const v=vals(line);if(!v.length)continue;const result=v.find(x=>x.star)||v[0],limit=requirement(all,i,result.unit)||(v.length>1?v[v.length-1]:null);if(!limit||limit===result||limit.unit!==result.unit)continue;
// Critical safeguard: do not infer FAIL from numbers. Require explicit SGS evidence on the same row.
if(!(/\bFAIL\b|exceed(?:s|ed)?\s+(?:the\s+)?limit/i.test(line)||result.star))continue;
out.push({substance:name,result:result.raw,limit:limit.raw})}});const d=new Map();out.forEach(x=>d.set(`${x.substance}|${x.result}|${x.limit}`.toUpperCase(),x));return[...d.values()]}
function ui(){if($('failedItemsV32'))return;const s=$('substance');if(!s)return;const f=s.closest('.field'),rf=$('result').closest('.field'),lf=$('limit').closest('.field');[f,rf,lf].forEach(x=>x.style.display='none');const w=document.createElement('div');w.id='failedItemsV32';w.className='field full';w.innerHTML='<label>Failed Items *</label><div id="failedItemsRows"></div><button type="button" class="btn" id="addFailedItemV32">+ Add Failed Item</button>';f.parentElement.insertBefore(w,f);$('addFailedItemV32').onclick=()=>{items.push({substance:'',result:'',limit:''});render()};render()}
function render(){const h=$('failedItemsRows');if(!h)return;h.innerHTML=items.map((x,i)=>`<div style="display:grid;grid-template-columns:1.5fr 1fr 1fr auto;gap:8px;margin:8px 0"><input data-k="substance" data-i="${i}" value="${esc(x.substance)}" placeholder="Substance / Test Item"><input data-k="result" data-i="${i}" value="${esc(x.result)}" placeholder="Measured Result"><input data-k="limit" data-i="${i}" value="${esc(x.limit)}" placeholder="Limit"><button type="button" class="btn danger" data-r="${i}">Remove</button></div>`).join('');h.querySelectorAll('[data-k]').forEach(n=>n.oninput=()=>{items[+n.dataset.i][n.dataset.k]=n.value;sync()});h.querySelectorAll('[data-r]').forEach(n=>n.onclick=()=>{items.splice(+n.dataset.r,1);render()});sync()}
function sync(){const x=items[0]||{};$('substance').value=x.substance||'';$('result').value=x.result||'';$('limit').value=x.limit||''}
function mail(c){const its=c.failedItems?.length?c.failedItems:items,p=$('emailPreview');if(!p)return;const list=its.map((x,i)=>`${i+1}. ${x.substance}\n   Test result: ${x.result}\n   Requirement / limit: ${x.limit}`).join('\n\n');p.textContent=`Subject: SGS RSL Failure Notification | ${c.article} | Report ${c.report}\n\nDear ${c.supplier} Team,\n\nSGS RSL Report ${c.report} for Fabric Article ${c.article}${c.po?`, PO(s) ${c.po}`:''}${c.lot?`, Lot(s) ${c.lot}`:''} has a FAIL result.\n\nFailed Items\n\n${list}\n\nImmediate containment is required. Please immediately quarantine all affected material and stop shipment, cutting, production use, transfer or release until written disposition is provided.\n\nPlease reply with the following information:\n\nImmediate Containment\n1. How much material is affected? Include quantity, unit, PO(s) and lot(s).\n2. Where is the affected material currently located?\n3. What is the current status of the failed material?\n4. What immediate actions have been completed?\n5. Is all affected material on hold and physically segregated? Please provide evidence.\n6. Will the material be held, reworked, dropped, destroyed or otherwise disposed of?\n\nCAPA and Retest\n7. Please provide a formal Root Cause Analysis.\n8. Please provide the Corrective Action Plan, responsible owner and target completion date.\n9. Please provide additional Preventive Actions to prevent recurrence.\n10. Please provide the SGS retest plan, including the full required test scope, TRF number, all affected lot numbers, sample submission date and expected report completion date.\n11. Please confirm how the corrective actions and retest results will be verified before any material is released.\n\nCAPA due date: ${c.dueDate}\n\nBest regards,\nVuori Product Integrity & Compliance`;$('emailCard')?.classList.remove('hidden')}
function install(){ui();const a=$('analyzePdf'),base=a?.onclick;if(a)a.onclick=async function(e){await base?.call(this,e);const f=$('pdfFile')?.files?.[0];if(!f)return;try{const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await f.arrayBuffer())}).promise;let out=[];for(let i=1;i<=pdf.numPages;i++)out=out.concat(parse(rows(await(await pdf.getPage(i)).getTextContent())));items=out.length<=12?out:[];render();const x=$('parseAlert');if(x){x.textContent=items.length?`Automated extraction completed. ${items.length} failed item(s) listed. Verify each item against the original PDF.`:'No row with an explicit FAIL, Exceed the limit, or starred result was confirmed. Add the failed items manually.';x.classList.remove('hidden')}}catch(err){console.error('V3.2B',err)}};const c=$('createCase'),cb=c?.onclick;if(c)c.onclick=function(e){sync();if(!items.length||items.some(x=>!x.substance||!x.result||!x.limit)){alert('Complete each Failed Item before creating the case.');return}const n=cases.length;cb?.call(this,e);if(cases.length>n){cases[0].failedItems=JSON.parse(JSON.stringify(items));localStorage.setItem(CASE_KEY,JSON.stringify(cases));renderCases?.();mail(cases[0])}};window.generateEmail=mail;document.addEventListener('click',e=>{const b=e.target.closest('[data-email]');if(b){const c=cases.find(x=>x.id===b.dataset.email);if(c)setTimeout(()=>mail(c),0)}},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
